spring:
  application:
    name: user_manage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://49.233.77.228:3316?serverTimezone=PRC
#    username: linxing
#    password: Hmlx123.
    url: jdbc:mysql://localhost:3306?serverTimezone=PRC
    username: root
    password: 123456
    hikari:
      connection-test-query: select 1
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis:
  type-aliases-package: com.lx.usermanage.domain
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.jc.usermanage.dao: debug
#解决重定向后路径带jsessionid
server:
  servlet:
    session:
      tracking-modes: cookie
  port: 8848
